thorswap/SwapKit

apps/vite-playground/package.json, apps/vite-playground/src/WalletPicker.tsx, apps/vite-playground/src/index.css, apps/vite-playground/src/main.tsx, apps/vite-playground/src/swapKitClient.ts, apps/vite-playground/vite.config.ts, yarn.lock
=> docs: setup keystore wallet on playground

.changeset/brave-pumas-cover.md, packages/swapkit/swapkit-api/src/types/quote.ts
Types needed for tracking streaming swap progress
=> Add types for streaming swap tracker

packages/swapkit/swapkit-api/src/types/quote.ts
=> Straming tx status

.changeset/late-bees-teach.md, .vscode/settings.json, packages/swapkit/swapkit-core/src/client/index.ts, packages/swapkit/types/src/commonTypes.ts, packages/toolboxes/toolbox-cosmos/src/thorchainUtils/types/client-types.ts, packages/toolboxes/toolbox-cosmos/src/toolbox/BaseCosmosToolbox.ts, packages/toolboxes/toolbox-cosmos/src/toolbox/binance.ts, packages/toolboxes/toolbox-cosmos/src/toolbox/gaia.ts, packages/toolboxes/toolbox-cosmos/src/toolbox/thorchain.ts, packages/toolboxes/toolbox-utxo/src/toolbox/BaseUTXOToolbox.ts, packages/toolboxes/toolbox-utxo/src/toolbox/bch.ts
& custom wallets implementation types
=> chore: add private keys & signer handling for utxo & cosmos 

packages/swapkit/swapkit-api/src/types/quote.ts
=> Lending tx type

.changeset/loud-coins-brake.md, packages/swapkit/swapkit-api/src/types/quote.ts, packages/swapkit/swapkit-core/src/client/index.ts, packages/swapkit/swapkit-core/src/client/types.ts, packages/swapkit/types/src/commonTypes.ts
=> chore: ensure recipient address exists and is valid 

.changeset/dull-meals-impress.md, packages/swapkit/swapkit-entities/src/entities/assetAmount.ts
=> Fix bsc min amount

packages/swapkit/types/src/network.ts
Change the explorer for Maya Protocol to https://www.mayascan.org
=> Change Maya explorer

packages/swapkit/types/src/network.ts, packages/toolboxes/cosmos/src/index.ts, packages/toolboxes/cosmos/src/thorchainUtils/types/client-types.ts, packages/toolboxes/cosmos/src/toolbox/BaseCosmosToolbox.ts, packages/toolboxes/cosmos/src/toolbox/kujira.ts, packages/toolboxes/cosmos/src/types.ts, packages/toolboxes/cosmos/src/util.ts, packages/wallets/keystore/src/keystore.ts
=> [FEAT]: KujiraToolbox

.changeset/hungry-pumpkins-exist.md, internal/config/index.js, internal/node-playground/index.ts, packages/swapkit/helpers/src/modules/__tests__/swapKitNumber.test.ts, packages/swapkit/helpers/src/modules/bigIntArithmetics.ts
Most important change is with `this.#arithmetic` method and how it's retrieving decimals for next instance/number.
=> fix: division precision on shifted & extended decimals

packages/wallets/keepkey/src/chains/utxo.ts
Features:
========
* this PR isolates the type work done the UTXO module for KeepKey
=> UTXO type cleanup

.changeset/old-cougars-stare.md, internal/config/package.json, internal/playground/package.json, internal/playground/src/App.tsx, internal/playground/src/WalletPicker.tsx, internal/playground/src/swapKitClient.ts, internal/playground/vite.config.ts, package.json, packages/swapkit/core/src/client/index.ts, packages/swapkit/helpers/src/modules/swapKitError.ts, packages/swapkit/sdk/package.json, packages/swapkit/sdk/src/index.ts, packages/swapkit/types/src/commonTypes.ts, packages/swapkit/types/src/wallet.ts, packages/toolboxes/cosmos/src/cosmosClient.ts, packages/toolboxes/cosmos/src/util.ts, packages/toolboxes/utxo/src/toolbox/bch.ts, packages/wallets/keepkey/package.json, packages/wallets/keepkey/src/chains/binance.ts, packages/wallets/keepkey/src/chains/cosmos.ts, packages/wallets/keepkey/src/chains/evm.ts, packages/wallets/keepkey/src/chains/thorchain.ts, packages/wallets/keepkey/src/chains/utxo.ts, packages/wallets/keepkey/src/helpers/coins.ts, packages/wallets/keepkey/src/index.ts, packages/wallets/keepkey/src/keepkey.ts, packages/wallets/keepkey/src/modules.d.ts, packages/wallets/keepkey/tsconfig.json, packages/wallets/keepkey/vite.config.ts, pnpm-lock.yaml
=> feat: KeepKey Wallet

.changeset/curvy-maps-return.md, packages/swapkit/chainflip/src/broker.ts
https://discord.com/channels/824147014140952596/824147608377098241/1209981062042619955
=> Fix chainflip deposit channel

packages/wallets/xdefi/src/index.ts, packages/wallets/xdefi/src/walletHelpers.ts
=> Add Mayachain x XDEFI support

packages/toolboxes/cosmos/src/thorchainUtils/messages.ts, packages/wallets/xdefi/src/xdefiWallet.ts
I forgot to add the toolbox in #662 - here is a fix to have the functions exposed in XDEFI wallet.
=> Fix XDEFI x Mayachain support

packages/swapkit/core/src/client/old.ts, packages/swapkit/thorchain/src/client.ts
debugged that in my browser, its not an error object, instead a plain string:
this happened when I rejected the XDEFI tx popup.
=> Fix error.message: Cannot read properties of undefined (reading 'toLowerCase')

packages/toolboxes/cosmos/src/thorchainUtils/messages.ts, packages/toolboxes/cosmos/src/thorchainUtils/registry.ts, packages/toolboxes/cosmos/src/toolbox/thorchain.ts, packages/wallets/xdefi/src/walletHelpers.ts
Its a little mess when we have the chain parameter in so many functions, to reuse thorchain code.
Ofc we could copy paste the thorchain + thorchainUtils folder to dedicated mayachain folder. but that sounded also quite overheady.
=> fix Mayachain messages + XDEFI deposit

.github/workflows/build-test-publish.yml, .size-limit.js, packages/swapkit/helpers/package.json, packages/wallets/ledger/package.json, packages/wallets/trezor/package.json, packages/wallets/wc/package.json
* chore: cleanup for stable
* chore: step by step... [wip]
* chore: update types and imports
* fix: build shenanigans
=> chore: merge helpers, type core & plugins (#707)

.changeset/purple-shoes-swim.md, packages/swapkit/helpers/src/helpers/asset.ts, packages/swapkit/helpers/src/modules/__tests__/assetValue.test.ts
added missing details.
fixed tests.
=> fix: OP/ARB asset details for ETH

packages/swapkit/thorchain/src/mayaPlugin.ts
this got lost during the refactoring from the old.ts
=> mayaPlugin: add registerMayaname again

.changeset/slow-baboons-judge.md, packages/swapkit/core/src/client.ts, packages/swapkit/helpers/src/types/sdk.ts, packages/toolboxes/evm/src/toolbox/BaseEVMToolbox.ts
Core package contained the evm approval logic.
Moved it to the BaseEVMToolbox and have core calling it through the wallet.
=> Move approve to evm toolbox

packages/wallets/xdefi/src/walletHelpers.ts
Disable the approve function for xdefi wallet
=> Remove xdefi wallet approve function

packages/swapkit/api/src/index.ts, packages/swapkit/api/src/thorswapApiV2/endpoints.ts, packages/swapkit/api/src/thorswapApiV2/types.ts
=> Tracker v2 api

.changeset/clever-yaks-divide.md, packages/swapkit/chainflip/src/broker.ts, packages/swapkit/chainflip/src/index.ts, packages/swapkit/chainflip/src/types.ts
Accept boosted fee and CCM metadata params in deposit channel
=> Boosted swaps and CCM metadata

.changeset/soft-bugs-sort.md, packages/swapkit/api/src/thorswapApi/types.ts, packages/swapkit/helpers/src/modules/__tests__/assetValue.test.ts, packages/swapkit/helpers/src/modules/assetValue.ts
See discord message for imports/pipeline issues
=> Missing prop and AssetValue utilities
